apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: myjenkins
  namespace: jenkins
repository: https://charts.helm.sh/stable
chart: jenkins
version: 0.32.4
valueFiles:
  - ../../example/jenkins/values.yaml
