apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generators:
- generator.yaml
vars:
- name: VALUE_FROM_CONFIGMAP
  objref:
    kind: ConfigMap
    name: myconfig
    namespace: myns
    apiVersion: v1
  fieldref:
    fieldpath: data.mykey
